services:
  tasksmdb:
    container_name: tasksmdb
    environment:
      - POSTGRES_DB=tasksmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
       - "5432:5432"
    volumes:
       - postgres_tasksmdb:/var/lib/postgresql/data
 
  messagebus:
    container_name: messagebus
    hostname: tasksm-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"